name: "Linting & tests"

on: push

jobs:
  name: "Linting"
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: "Intall package"
      run: npm install
    - name: "execute Linter"
      run: npm run lint
